### ISSUE TITLE
Panic when Out of Bounds

### ISSUE THREAD

**Issue by rfuzz** [jetstream0/BMP-Rust#5]
Hi,

I encountered a situation where the `BMP::change_color_of_pixel` function can cause a panic. If the parameters specify coordinates that are outside the bounds of the BMP image, it results in an overflow panic:

```shell
# Generate a 10x10 BMP image
convert -size 10x10 xc:white output.bmp
```

```rust
use bmp_rust::bmp::BMP;

fn main() {
    let mut bmp_from_file = BMP::new_from_file("output.bmp");
    match bmp_from_file.change_color_of_pixel(20, 20, [233, 71, 255, 255]) {
        Ok(_) => { println!("Success"); }
        Err(e) => { eprintln!("{}", e); }
    };
}
```

After running the program, it panics with the following error:

```shell
thread 'main' panicked at /home/ubuntu/BMP-Rust/src/bmp.rs:1480:11:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Additionally, `BMP::fill_bucket` has a similar issue where passing out-of-bounds coordinates directly causes a panic.

```shell
thread 'main' panicked at /home/ubuntu/BMP-Rust/src/bmp.rs:1177:38:
Out of bounds access
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Other functions might also have similar issues. It would be better if out-of-bounds access errors were caught and an appropriate error message was returned.

Version: `commit a84e0c6e380652c8775818cc59515f73b244083c`

**Comment by stjet** [comment]
Thanks for the report.

I wrote this when I was learning Rust and not that great at programming in general. So code quality is not very good.

But, I think this would probably be a simple case of adding bounds checking to `change_color_of_pixel`, `change_color_of_pixel_efficient`,  `get_color_of_pixel`, and `get_color_of_pixel_efficient`, then changing a bunch of `.unwrap()`s to `?` (and adding the new error type). I will do that if I ever come back to this crate, but frankly in my own code that uses this crate, I never go out of bounds, so the motivation might be lacking.

PS: Are you an AI?

**Comment by rfuzz** [comment]
Under normal circumstances, these issues might not occur. However, when handling abnormal data, the program may crash. It's better to handle such exceptions gracefully rather than letting the program panic. Using `?` instead of `unwrap()` is definitely a better choice.

PS: I'm not an AI; I'm not a native English speaker and used AI-assisted translation. I'm also working on fuzz testing using a Rust Fuzz Target generator I wrote :)
